### ISSUE TITLE
Extend Validity

### ISSUE THREAD

**Issue by stefan313** [stefan313/HenkeNet-UserDB#11]
Änderung:
expiration_date werden nur auf "YYYY-(04-30, 10-31)" gesetzt.
In der Maske Extend Validity wird nur noch die Anzahl der Semester angenommen (Maximal 2)
Die Felder eingenommenes Geld und Datum werden auf Read-Only gesetzt
Kommentar ist weiterhin ein editierbares Feld.

**Comment by tleemann** [comment]
Geändert mit letztem Commit. Was soll passieren wenn Account bereits verlängert? Einfache Implementierung für bereits verlängerte Accounts ist aber nun vorhanden.
