### ISSUE TITLE
Account-Erstellung

### ISSUE THREAD

**Issue by stefan313** [stefan313/HenkeNet-UserDB#12]
Da man für die Erstellung eines Accounts nicht zwingend 10€ zahlen muss, wird bei der Erstellung vor einem Bezahltermin ein expiration_date auf kurz danach gesetzt. Falls man gleich 10€ zahlen kann, ist es möglich normal zu verlänger über die Funktion "Extend Validity".

Zeitäume:
Zwischen März und August wird expiration_date auf den 30. April gesetzt.
Zwischen  September und Februar wird expiration_date auf den 31. Oktober gesetzt.

**Comment by tleemann** [comment]
Geändert mit letztem Commit.
