### ISSUE TITLE
Password bei Account-Bearbeitung nicht immer setzten.

### ISSUE THREAD

**Issue by tleemann** [stefan313/HenkeNet-UserDB#14]
Da wir die Passwörter ja nicht mehr vom Server laden bleibt das Feld Passwort in der "Edit"-Maske leer.
Wenn allerdings die Änderungen übernommen werden, wird das Password IN JEDEM FALL überschrieben, d.h. wenn das Passwort nicht neu gesetzt wurde, wird es mit Leer überschrieben. Dies sollte nicht so sein.
Passwort nur neu schreiben, wenn die Textfelder gefüllt sind.
Bitte ändern.

**Comment by stefan313** [comment]
hierfuer gibts im User ein Flag! (bool passwordChanged())

**Comment by tleemann** [comment]
Okay, Fall wurde doch schon beachtet. Issue closed.
